[package]
name = "petty-xpath1"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0"
thiserror = "2.0.17"

[dev-dependencies]
# For testing XML/JSON data sources
roxmltree = "0.21.1"
serde_json = "1.0"
